/* Seleccionar todos los hoteles */
SELECT * FROM HOTELES;

/* Seleccionar todos los hoteles que estén (por ejemplo) en Sevilla */
SELECT * FROM HOTELES WHERE CIUDAD LIKE 'SEVILLA';

/* Seleccionar todos los hoteles comprendidos entre una y tres estrellas */
SELECT * FROM HOTELES WHERE ESTRELLAS BETWEEN 1 AND 3;

/* Seleccionar todos los hoteles, donde la noche cueste entre 40 y 60 */
SELECT * FROM HOTELES
WHERE ID IN (SELECT HOTELES_ID
           FROM HABITACIONES
           WHERE PRECIO_NOCHE BETWEEN 40 AND 60);

/* Esta consulta tiene que ver con la anterior. Por ejemplo; cuando al usuario le salgan
todos los hoteles que tienen habitaciones con un precio de entre 40 y 60 la noche y seleccione uno de los hoteles,
lo ideal sería mostrar esas habitaciones ya filtradas del correspondiente hotel y todos sus detalles */
SELECT HO.NOMBRE, HA.DESCRIPCION, HA.NUM_CAMAS, HA.NUM_PLANTA, HA.PRECIO_NOCHE
FROM HOTELES HO, HABITACIONES HA
WHERE HO.ID = HA.HOTELES_ID
AND HA.PRECIO_NOCHE BETWEEN 40 AND 60;

/* Y si el usuario lo quisiera, se podrían ordenar las habitaciones de más baratas a más caras,
haciendo así más completa la consulta anterior */
SELECT HO.NOMBRE, HA.DESCRIPCION, HA.NUM_CAMAS, HA.NUM_PLANTA, HA.PRECIO_NOCHE
FROM HOTELES HO, HABITACIONES HA
WHERE HO.ID = HA.HOTELES_ID
AND HA.PRECIO_NOCHE BETWEEN 40 AND 60
ORDER BY PRECIO_NOCHE ASC;

/* U ordenando de las habitaciones más caras a las más baratas */
SELECT HO.NOMBRE, HA.DESCRIPCION, HA.NUM_CAMAS, HA.NUM_PLANTA, HA.PRECIO_NOCHE
FROM HOTELES HO, HABITACIONES HA
WHERE HO.ID = HA.HOTELES_ID
AND HA.PRECIO_NOCHE BETWEEN 40 AND 60
ORDER BY PRECIO_NOCHE DESC;

/* Seleccionar las imágenes de un hotel en concreto filtrando por el nombre del hotel */
SELECT IMG_PATH
FROM IMAGENES_HOTELES
WHERE HOTELES_ID IN (SELECT ID
                    FROM HOTELES
                    WHERE NOMBRE LIKE 'Monterrey Costa');

/* Seleccionar todas las habitaciones de un hotel en concreto filtrando por el nombre del hotel */
SELECT *
FROM HABITACIONES
WHERE HOTELES_ID IN (SELECT ID
                   FROM HOTELES
                   WHERE NOMBRE LIKE 'Hotel Polígono Sur');

/* Seleccionar todas las habitaciones de un hotel en concreto y sólo las familiares */
SELECT * FROM HABITACIONES
WHERE DESCRIPCION LIKE 'Familiar'
AND HOTELES_ID IN (SELECT ID
                  FROM HOTELES
                  WHERE NOMBRE LIKE 'Hotel Zenit Barcelona');

/* Seleccionar todas las habitaciones de un hotel en concreto, sólo las familiares 
y con un precio por noche comprendido entre 20 y 50 */
SELECT * FROM HABITACIONES
WHERE DESCRIPCION LIKE 'Familiar'
AND PRECIO_NOCHE BETWEEN 20 AND 50
AND HOTELES_ID IN (SELECT ID
                  FROM HOTELES
                  WHERE NOMBRE LIKE 'Hotel Zenit Barcelona');

/* Seleccionar todas las imágenes de una habitación en concreto */
SELECT IMG_PATH FROM IMAGENES_HABITACIONES
WHERE HABITACIONES_ID = 1;

/* Seleccionar todas las valoraciones de un hotel en concreto */
SELECT U.NOMBRE, DESCRIPCION, PUNTUACION, FECHA
FROM VALORACIONES, USUARIOS U
WHERE U.CORREO LIKE USUARIOS_CORREO
AND HOTELES_ID IN (SELECT ID
                  FROM HOTELES
                  WHERE NOMBRE LIKE 'Monterrey Costa');

/* Seleccionar todas las valoraciones de un usuario en concreto */
SELECT DESCRIPCION, PUNTUACION, FECHA
FROM VALORACIONES WHERE USUARIOS_CORREO LIKE 'diego.fernandez@iespoligonosur.org';

/* Seleccionar todas las reservas */
SELECT U.CORREO, U.NOMBRE, U.APELLIDOS, R.FECHA_RESERVA, R.FECHA_ENTRADA,
R.FECHA_SALIDA, R.NUM_PERSONAS, HO.NOMBRE, HA.DESCRIPCION, HA.NUM_HABITACION,
HA.NUM_PLANTA, HA.PRECIO_NOCHE, HA.NUM_CAMAS, TP.DESCRIPCION, TP.PRECIO
FROM USUARIOS U, RESERVAS R, HOTELES HO, HABITACIONES HA, TIPOS_PENSIONES TP, RESERVAS_HABITACIONES RH
WHERE U.CORREO LIKE R.USUARIOS_CORREO
AND R.ID = RH.RESERVAS_ID
AND HO.ID = TP.HOTELES_ID
AND HA.ID = RH.HABITACIONES_ID
AND TP.ID = R.TIPOS_PENSIONES_ID;

/* Seleccionar todas las reservas de un hotel en concreto */
SELECT U.CORREO, U.NOMBRE, U.APELLIDOS, R.FECHA_RESERVA, R.FECHA_ENTRADA,
R.FECHA_SALIDA, R.NUM_PERSONAS, HO.NOMBRE, HA.DESCRIPCION, HA.NUM_HABITACION,
HA.NUM_PLANTA, HA.PRECIO_NOCHE, HA.NUM_CAMAS, TP.DESCRIPCION, TP.PRECIO
FROM USUARIOS U, RESERVAS R, HOTELES HO, HABITACIONES HA, TIPOS_PENSIONES TP, RESERVAS_HABITACIONES RH
WHERE U.CORREO LIKE R.USUARIOS_CORREO
AND R.ID = RH.RESERVAS_ID
AND HO.ID = TP.HOTELES_ID
AND HA.ID = RH.HABITACIONES_ID
AND TP.ID = R.TIPOS_PENSIONES_ID
AND HO.ID = 2;

/* Seleccionar todas las reservas de una habitación en concreto de un hotel en concreto */
SELECT U.CORREO, U.NOMBRE, U.APELLIDOS, R.FECHA_RESERVA, R.FECHA_ENTRADA,
R.FECHA_SALIDA, R.NUM_PERSONAS, HO.NOMBRE, HA.DESCRIPCION, HA.NUM_HABITACION,
HA.NUM_PLANTA, HA.PRECIO_NOCHE, HA.NUM_CAMAS, TP.DESCRIPCION, TP.PRECIO
FROM USUARIOS U, RESERVAS R, HOTELES HO, HABITACIONES HA, TIPOS_PENSIONES TP, RESERVAS_HABITACIONES RH
WHERE U.CORREO LIKE R.USUARIOS_CORREO
AND R.ID = RH.RESERVAS_ID
AND HO.ID = 1
AND HO.ID = TP.HOTELES_ID
AND HA.ID = 1
AND TP.ID = R.TIPOS_PENSIONES_ID;

/* Seleccionar todas las reservas de un usuario en concreto filtrando por nombre */
SELECT U.CORREO, U.NOMBRE, U.APELLIDOS, R.FECHA_RESERVA, R.FECHA_ENTRADA,
R.FECHA_SALIDA, R.NUM_PERSONAS, HO.NOMBRE, HA.DESCRIPCION, HA.NUM_HABITACION,
HA.NUM_PLANTA, HA.PRECIO_NOCHE, HA.NUM_CAMAS, TP.DESCRIPCION, TP.PRECIO
FROM USUARIOS U, RESERVAS R, HOTELES HO, HABITACIONES HA, TIPOS_PENSIONES TP, RESERVAS_HABITACIONES RH
WHERE R.ID = RH.RESERVAS_ID
AND U.CORREO LIKE R.USUARIOS_CORREO
AND HO.ID = TP.HOTELES_ID
AND HA.ID = RH.HABITACIONES_ID
AND TP.ID = R.TIPOS_PENSIONES_ID
AND U.CORREO LIKE (SELECT CORREO
				  FROM USUARIOS
				  WHERE NOMBRE LIKE 'Diego Jesús');

/* Seleccionar todas las reservas de un usuario en concreto filtrando por apellido */
SELECT U.CORREO, U.NOMBRE, U.APELLIDOS, R.FECHA_RESERVA, R.FECHA_ENTRADA,
R.FECHA_SALIDA, R.NUM_PERSONAS, HO.NOMBRE, HA.DESCRIPCION, HA.NUM_HABITACION,
HA.NUM_PLANTA, HA.PRECIO_NOCHE, HA.NUM_CAMAS, TP.DESCRIPCION, TP.PRECIO
FROM USUARIOS U, RESERVAS R, HOTELES HO, HABITACIONES HA, TIPOS_PENSIONES TP, RESERVAS_HABITACIONES RH
WHERE R.ID = RH.RESERVAS_ID
AND U.CORREO LIKE R.USUARIOS_CORREO
AND HO.ID = TP.HOTELES_ID
AND HA.ID = RH.HABITACIONES_ID
AND TP.ID = R.TIPOS_PENSIONES_ID
AND U.CORREO LIKE (SELECT CORREO
				  FROM USUARIOS
				  WHERE APELLIDOS LIKE 'Fernández Raposo');

/* Seleccionar todas las reservas de un usuario en concreto filtrando por correo */
SELECT U.CORREO, U.NOMBRE, U.APELLIDOS, R.FECHA_RESERVA, R.FECHA_ENTRADA,
R.FECHA_SALIDA, R.NUM_PERSONAS, HO.NOMBRE, HA.DESCRIPCION, HA.NUM_HABITACION,
HA.NUM_PLANTA, HA.PRECIO_NOCHE, HA.NUM_CAMAS, TP.DESCRIPCION, TP.PRECIO
FROM USUARIOS U, RESERVAS R, HOTELES HO, HABITACIONES HA, TIPOS_PENSIONES TP, RESERVAS_HABITACIONES RH
WHERE R.ID = RH.RESERVAS_ID
AND U.CORREO LIKE R.USUARIOS_CORREO
AND HO.ID = TP.HOTELES_ID
AND HA.ID = RH.HABITACIONES_ID
AND TP.ID = R.TIPOS_PENSIONES_ID
AND U.CORREO LIKE 'diego.fernandez@iespoligonosur.org';


/* HACER SELECT DE SI UNA HABITACIÓN ESTÁ DISPONIBLE PARA RESERVARLA O NO */
SELECT HO.NOMBRE, HA.DESCRIPCION, HA.PRECIO_NOCHE
FROM HOTELES HO, HABITACIONES HA
WHERE HO.ID = HA.HOTELES_ID
AND HA.ID NOT IN (SELECT HABITACIONES_ID
                 FROM RESERVAS_HABITACIONES);

/* HACER SELECT DE SI UNA HABITACIÓN ESTÁ DISPONIBLE PARA RESERVARLA O NO FILTRANDO POR FECHA DE ENTRADA Y DE SALIDA */

/***************************************************/
SELECT COUNT(*)
FROM HOTELES HO, HABITACIONES HA, RESERVAS R, RESERVAS_HABITACIONES RH
WHERE HO.ID = HA.HOTELES_ID
AND R.ID = RH.RESERVAS_ID
AND HA.ID = RH.HABITACIONES_ID
AND R.FECHA_ENTRADA >= (SELECT CURDATE())